COMMAND_DEFINITIONS = [
    {
        "keyword": "open",
        "usage": "open <app_alias>",
        "min_args": 1,
        "handler_name": "_handle_open",
        "dangerous": False,
    },
    {
        "keyword": "search",
        "usage": "search file <query>",
        "min_args": 2,
        "first_arg_equals": "file",
        "handler_name": "_handle_search",
        "dangerous": False,
    },
    {
        "keyword": "sys",
        "usage": "sys info",
        "min_args": 1,
        "max_args": 1,
        "first_arg_equals": "info",
        "handler_name": "_handle_sys",
        "dangerous": False,
    },
    {
        "keyword": "capability",
        "usage": "capability <domain> <action> [args]",
        "min_args": 2,
        "handler_name": "_handle_capability",
        "dangerous": False,
    },
    {
        "keyword": "smart",
        "usage": "smart <request>",
        "min_args": 1,
        "handler_name": "_handle_smart",
        "dangerous": False,
    },
    {
        "keyword": "profile",
        "usage": "profile <strict|balanced|power|explain-only>",
        "min_args": 1,
        "max_args": 1,
        "handler_name": "_handle_profile",
        "dangerous": False,
    },
    {
        "keyword": "proj",
        "usage": "proj open <name>",
        "min_args": 2,
        "handler_name": "_handle_proj",
        "dangerous": False,
    },
    {
        "keyword": "clip",
        "usage": "clip <add|show|clear> [text]",
        "min_args": 1,
        "handler_name": "_handle_clip",
        "dangerous": False,
    },
    {
        "keyword": "mode",
        "usage": "mode <focus|game> on | mode off",
        "min_args": 0,
        "handler_name": "_handle_mode",
        "dangerous": False,
    },
    {
        "keyword": "net",
        "usage": "net <ping|dns|ip> [host]",
        "min_args": 1,
        "handler_name": "_handle_net",
        "dangerous": False,
    },
]
